version: 2
jobs:
  build:
    docker:
      - image: "cimg/node:18.12.1"
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # Fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: install
          command: yarn install
      - run:
          name: build
          command: yarn build
      - run:
          name: release
          command: yarn run semantic-release || true
workflows:
  version: 2
  master:
    jobs:
      - build:
          context: devops-dev
          filters:
            branches:
              only:
                - master
