version: 2
jobs:
  build:
    docker:
      - image: "cimg/node:22.5.1"
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-packages-{{ checksum "package-lock.json" }}
      - run:
          name: Install NPM Packages
          command: |
            if [ -d "node_modules" ]; then
              npm rebuild
            else
              npm ci --include=dev
            fi
      - run:
          name: build
          command: npm run build
      - run:
          name: release
          command: npm run semantic-release || true
      - save_cache:
          key: npm-packages-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
workflows:
  version: 2
  main:
    jobs:
      - build:
          context: devops-dev
          filters:
            branches:
              only:
                - main
