name: Auto approve
on: pull_request_target
permissions:
  pull-requests: write
jobs:
  auto-approve:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
    steps:
      - uses: hmarr/auto-approve-action@v3
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
